xp_requirements:
  agility:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  alchemy:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  combat:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  cooking:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  defense:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  enchanting:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  excavation:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  farming:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  fishing:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  mining:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  sorcery:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0
  woodcutting:
    max_lvl: 50
    multiplier: 100.0
    base: 100.0

xp_event:
  modifier: 1.0
  active: false

stat:
  health:
    base: 0.0
    perLvl: 1.0
    skills: cooking,farming,fishing
  strength:
    base: 0.0
    perLvl: 2.5
    skills: woodcutting
  fortune:
    base: 0.0
    perLvl: 2.05
    skills: woodcutting,mining
  critchance:
    base: 10.0
    perLvl: 1.25
    skills: combat
  critdamage:
    base: 50.0
    perLvl: 1.02
    skills: combat
  attackspeed:
    base: 0.0
    perLvl: 0.35
    skills: combat
  toughness:
    base: 0.0
    perLvl: 0.332
    skills: excavation,defense,mining
  speed:
    base: 0.0
    perLvl: 0.008
    skills: agility
  wisdom:
    base: 100
    perLvl: 40.0
    skills: alchemy,sorcery,enchanting