name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
api-version: '1.18'
main: com.gmail.willramanand.RamSkills.RamSkills
softdepend: [Vault]
commands:
  skills:
    description: Base command for RamSkills.
    aliases: [sk]
permissions:
  skills.xp:
    default: op
  skills.lvl:
    default: op
  skills.xpevent:
    default: op
