name: RamSkills
version: 1.0.0-SNAPSHOT
description: This plugin adds skills and abilities to your Spigot server.
author: ${project.author}
api-version: '1.18'
main: com.gmail.willramanand.RamSkills.RamSkills
depend:
softdepend: [Vault]
commands:
  skills:
    description: Base command for RamSkills.
permissions:
  skills.xp:
    default: op
  skills.lvl:
    default: op